#!/bin/sh -e

. ./build

go test -i ./xt
go test -v ./xt

go test -i ./strscan
go test -v ./strscan

go test -i ./duck
go test -v ./duck

go test -i ./entity
go test -v ./entity

go test -i ./typesys
go test -v ./typesys

go test -i ./ast
go test -v ./ast

go test -i ./parser
go test -v ./parser

go test -i ./compiler
go test -v ./compiler
