#!/bin/sh -e

. ./build

go test -i ./xt
go test -v ./xt

go test -i ./strscan
go test -v ./strscan

go test -i ./core
go test -v ./core

go test -i ./typesys
go test -v ./typesys

go test -i ./entity
go test -v ./entity

go test -i ./ast
go test -v ./ast

go test -i ./parser
go test -v ./parser

go test -i ./ir
go test -v ./ir

go test -i ./asm
go test -v ./asm

go test -i ./compiler
go test -v ./compiler

go test -i ./x86
go test -v ./x86

go test -i ./x86/linux
go test -v ./x86/linux
